title: Software development blog
author: atthealchemist
email: atthealchemist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about software development.
  Best practices and so on.

# social links
twitter_username: atthealchemist # DO NOT include the @ character, or else the build will fail!
github_username:  atthealchemist # DO NOT include the @ character, or else the build will fail!

theme: minima

show_excerpts: true # set to false to remove excerpts on the homepage
